name: PyTest
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install virtual env
        run: |
          pip3 install --upgrade pip3
          pip3 install virtualenv 
          virtualenv env
          pip3 install -r requirements.txt
      - name: Run test suite
        run: |
         source env/bin/activate
         pytest -sv --reruns 3